FROM python:latest
WORKDIR /app
RUN pip install --upgrade pip
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY /database /app/database
COPY /app /app/app
COPY config.ini .
COPY main.py .
ENV PYTHONPATH "${PYTHONPATH}:/app"
CMD [ "python", "main.py"]